In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9380, 3534, 7284, 8763],
 [9380, 3534, 7284, 7252],
 [9380, 5871, 7284, 1631],
 [7852, 2168, 6604, 3184, 2607],
 [7852, 2168, 6604, 3184, 7188],
 [1850, 9380, 9710, 7284, 6771],
 [9036, 2303, 5374, 3184]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9380 3534 7284 8763]
 [   0    0    0    0 9380 3534 7284 7252]
 [   0    0    0    0 9380 5871 7284 1631]
 [   0    0    0 7852 2168 6604 3184 2607]
 [   0    0    0 7852 2168 6604 3184 7188]
 [   0    0    0 1850 9380 9710 7284 6771]
 [   0    0    0    0 9036 2303 5374 3184]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

C:\Users\rashi_\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 207ms/step


array([[[ 0.01280255,  0.03391233,  0.01062303,  0.04739017,
          0.00089195,  0.01142148, -0.03143462, -0.02402028,
         -0.00082576, -0.03776406],
        [ 0.01280255,  0.03391233,  0.01062303,  0.04739017,
          0.00089195,  0.01142148, -0.03143462, -0.02402028,
         -0.00082576, -0.03776406],
        [ 0.01280255,  0.03391233,  0.01062303,  0.04739017,
          0.00089195,  0.01142148, -0.03143462, -0.02402028,
         -0.00082576, -0.03776406],
        [ 0.01280255,  0.03391233,  0.01062303,  0.04739017,
          0.00089195,  0.01142148, -0.03143462, -0.02402028,
         -0.00082576, -0.03776406],
        [ 0.04684975, -0.02676399, -0.01565975, -0.04662274,
         -0.04042633, -0.04784132, -0.0385957 ,  0.02038229,
         -0.02788266,  0.04647351],
        [-0.04302677,  0.03560671, -0.01147423, -0.00787884,
          0.02115562, -0.00470804, -0.03954872,  0.01568263,
         -0.04298538,  0.04130843],
        [-0.03562532,  0.02517703, -0.02178489, -0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 9380, 3534, 7284, 8763])

In [17]:
input_data = np.expand_dims(embedded_docs[0], axis=0)
prediction = model.predict(input_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step
